# Generated by Django 4.1.5 on 2023-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('idAuto', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Id de Auto')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de Auto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca de la Auto')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo de la Auto')),
                ('color', models.CharField(max_length=50, verbose_name='Color de la Auto')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
